Homework2 Nazarenko Arthut
Shurke/it-academy-summer-2021 pull request #17
Opened 2021-06-16 19:04 UTC by Athur2302

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-06-21 17:15 UTC, Athur2302 commented
что конкретно нужно доработать ?

2021-06-29 11:37 UTC, Shurke requested changes
1. Не хватает условий для 1-7 заданий.
2. Т.к. в 8й задания нет условий выполненных задач, то на данным момент не предоставляется возможным оценить их.
3. Плохой нейминг переменных. Переменным пора давать осознанные имена, чтобы было понятно, что в ней хранится.

2021-06-29 11:37 UTC, Shurke commented on src/2homework/task2.py
> +# ',','!','.','?',':','""',';'
Не думаю, что данный закомментированный код тут нужен.

2021-06-29 11:37 UTC, Shurke commented on src/2homework/task3.py
> +b = []
Здесь можно работать на прямую со строкой. Создавать список и потом получать из него строку не обязательно.

2021-06-29 11:37 UTC, Shurke commented on src/2homework/task4.py
> +english = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
Список всех букв английского алфавита можно получить из модуля `string`.

2021-06-29 11:37 UTC, Shurke commented on src/2homework/task7.py
> +    print("треугольник существует")
Не до конца выполнено условие задачи.

2021-06-29 11:37 UTC, Shurke commented on src/2homework/task5.py
> +print(b)
Перепроверьте решение. На данный момент не считает верным образом.

2021-07-06 15:14 UTC, closed without merging