Homework2: Anton Doroshenko
Shurke/it-academy-summer-2021 pull request #19
Opened 2021-06-16 21:00 UTC by AntonDoroshenko

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-06-20 13:30 UTC, Shurke requested changes
1. Почему во втором домашнем задании задачи из первого домашнего задания?
2. Стоит привыкать к осмысленным именам переменных. Также стоит еще раз перечитать РЕР8.
3. src/homework2/task_5.py - неверное решение.

2021-06-20 13:30 UTC, Shurke commented on src/homework2/task_1.py
> +# с использованием if elif else
А теперь рекомендую подумать над обобщенным решением.) Чтобы не нужно было столько условий.

2021-06-20 13:30 UTC, Shurke commented on src/homework2/task_2.py
> +list_7 = list_6.replace(';', '')
Можно через цикл сделать.
Итерироваться по строке, где находятся все знаки препинания.

2021-06-20 13:30 UTC, Shurke commented on src/homework2/task_3.py
> +
Пустая строка в начале файла не обязательна.

2021-06-20 13:30 UTC, Shurke commented on src/homework2/task_3.py
> +print("Новая строка без пробелов  --->  ", del_probel)
Дополнительные `print` - это только во время работы.
Когда отправляете решение, оставляем только тот, который выводит финальный ответ.

2021-06-20 13:30 UTC, Shurke commented on src/homework2/task_5.py
> +    print(second_numb, end=' ')
Неправильный алгоритм.
При введении номера числа, к примеру 5, ответ получается равным 5. Хотя 5-е число Фибоначчи - 3.
0, 1, 1, 2, 3, 5, 8, 13, 21, 34...

2021-06-20 13:30 UTC, Shurke commented on src/homework2/task_8.3.py
> +    print("Coding complete? Click 'Check' to earn cool rewards!")
Не нужно отправлять на проверку код с закомментированными строками.

2021-06-20 14:32 UTC, AntonDoroshenko commented
Добрый вечер!

1. Задачи из первого д/з попали случайно. Я когда пушил не заметил сразу
что отправил с задачами второй д/з и не сообразил как  нужно было правильно
отправлять.
2. PEP 8 перечитаю)
3. Ошибки/рекомендации исправлять и снова пушить? Если да, то какой срок на
исправление?

вс, 20 июн. 2021 г. в 16:30, Alexander Sereda ***@***.***>:

> *@Shurke* requested changes on this pull request.
>
>    1. Почему во втором домашнем задании задачи из первого домашнего
>    задания?
>    2. Стоит привыкать к осмысленным именам переменных. Также стоит еще
>    раз перечитать РЕР8.
>    3. src/homework2/task_5.py - неверное решение.
>
> ------------------------------
>
> In src/homework2/task_1.py
> <https://github.com/Shurke/it-academy-summer-2021/pull/19#discussion_r654935821>
> :
>
> > +# попытался сделать очень подробно для разных вариантов
> +# с использованием if elif else
>
> А теперь рекомендую подумать над обобщенным решением.) Чтобы не нужно было
> столько условий.
> ------------------------------
>
> In src/homework2/task_2.py
> <https://github.com/Shurke/it-academy-summer-2021/pull/19#discussion_r654935868>
> :
>
> > +list_2 = list.replace(',', '')
> +list_3 = list_2.replace(':', '')
> +list_4 = list_3.replace('!', '')
> +list_5 = list_4.replace('.', '')
> +list_6 = list_5.replace('?', '')
> +list_7 = list_6.replace(';', '')
>
> Можно через цикл сделать.
> Итерироваться по строке, где находятся все знаки препинания.
> ------------------------------
>
> In src/homework2/task_3.py
> <https://github.com/Shurke/it-academy-summer-2021/pull/19#discussion_r654935950>
> :
>
> > @@ -0,0 +1,17 @@
> +
>
> Пустая строка в начале файла не обязательна.
> ------------------------------
>
> In src/homework2/task_3.py
> <https://github.com/Shurke/it-academy-summer-2021/pull/19#discussion_r654936023>
> :
>
> > @@ -0,0 +1,17 @@
> +
> +print("Введите новую строку: ")
> +list = input()
> +
> +print("Количество пробелов:", list.count(" "))
> +
> +# указываем что необходимо удалить.
> +
> +del_probel = list.replace(" ", "")
> +print("Новая строка без пробелов  --->  ", del_probel)
>
> Дополнительные print - это только во время работы.
> Когда отправляете решение, оставляем только тот, который выводит финальный
> ответ.
> ------------------------------
>
> In src/homework2/task_5.py
> <https://github.com/Shurke/it-academy-summer-2021/pull/19#discussion_r654936198>
> :
>
> > +first_numb = second_numb = 1
> +print('Введите число')
> +n = int(input())
> +
> +print(first_numb, second_numb, end=' ')
> +
> +for i in range(2, n):
> +    first_numb, second_numb = first_numb, first_numb + second_numb
> +    print(second_numb, end=' ')
>
> Неправильный алгоритм.
> При введении номера числа, к примеру 5, ответ получается равным 5. Хотя
> 5-е число Фибоначчи - 3.
> 0, 1, 1, 2, 3, 5, 8, 13, 21, 34...
> ------------------------------
>
> In src/homework2/task_8.3.py
> <https://github.com/Shurke/it-academy-summer-2021/pull/19#discussion_r654936292>
> :
>
> > +# These "asserts" are used for self-checking and not for an auto-testing
> +# assert is_acceptable_password('short') == False
> +# assert is_acceptable_password('muchlonger') == True
> +# assert is_acceptable_password('ashort') == False
> +    print("Coding complete? Click 'Check' to earn cool rewards!")
>
> Не нужно отправлять на проверку код с закомментированными строками.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Shurke/it-academy-summer-2021/pull/19#pullrequestreview-687906876>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUMICM3XRR2YBHBA6VDMH5LTTXUPRANCNFSM462IDGWA>
> .
>

2021-06-27 10:04 UTC, Shurke reviewed
1. В задачах отсутствует условие.
2. Из-за отсутствия условий задач для 8й задачи, не представляется возможным их оценить.

Итоговая оценка 6.

2021-06-27 10:04 UTC, Shurke commented on src/homework2/task_2.py
> +Long_word = max(sentence, key=len)
Имя переменной должно быть с маленькой буквы.

2021-06-29 11:39 UTC, closed without merging