Homework2 ira amelishko
Shurke/it-academy-summer-2021 pull request #27
Opened 2021-06-17 12:33 UTC by AmelishkoIra

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-06-17 13:52 UTC, AmelishkoIra commented
Homework2

2021-06-20 13:11 UTC, Shurke requested changes
1. Галочки для отмечания в PR - это ваша работа.
2. Стоит привыкать к осмысленным именам переменных.
3. Стоит добавлять условия задачи в саму задачу.
4. src/task5.py - решена не верно.

2021-06-20 13:11 UTC, Shurke commented on src/task12.py
> +K = int(input("автобус вмещает человек "))
Имя переменной пишется с маленькой буквы (РЕР8).

2021-06-20 13:11 UTC, Shurke commented on src/task5.py
> +print("Искомое число:", n2)
Неправильный алгоритм.
При введении номера числа, к примеру 5, ответ получается равным 5. Хотя 5-е число Фибоначчи - 3.
0, 1, 1, 2, **3**, 5, 8, 13, 21, 34...

2021-06-27 18:03 UTC, Shurke reviewed
Стоит поработать еще над именами переменных.
Итоговая оценка 7.

2021-06-27 18:03 UTC, Shurke commented on src/task1.py
> +m = int(input("цена за товар, руб.:"))
Пропущено условие задачи.

2021-06-27 18:03 UTC, Shurke commented on src/task2.py
> +input_ = input(" ")
Пропущено условие задачи.

2021-06-27 18:03 UTC, Shurke commented on src/task3.py
> +input_ = input()
Пропущено условие задачи.

2021-06-27 18:03 UTC, Shurke commented on src/task4.py
> +input_ = input(" ")
Пропущено условие задачи.

2021-06-27 18:03 UTC, Shurke commented on src/task6.py
> +nomer_ = input("Введите число: ")
Пропущено условие задачи.

2021-06-27 18:03 UTC, Shurke commented on src/task7.py
> +a = int(input("a = "))
Пропущено условие задачи.

2021-06-29 12:15 UTC, closed without merging