Homework5: Stankiewich Jurij
Shurke/it-academy-summer-2021 pull request #52
Opened 2021-07-09 11:44 UTC by Jurij350

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-07-17 11:43 UTC, Shurke requested changes

2021-07-17 11:43 UTC, Shurke commented on src/homework5/task1/task1.py
> +def runner():
Данный подход не является гибким. Любое изменение в каком-либо импортированном файле приведет к тому, что в вашем. `runner` необходимо будет руками вносить изменения.

2021-07-17 11:43 UTC, Shurke commented on src/homework5/task1/task1.py
> +runner()
`runner` должен быть один.

2021-07-17 11:43 UTC, Shurke commented on src/homework5/task1/task1_hw_2_tasks.py
> +    import re
Импорты располагаются в самом начале модуля. Всегда.

2021-07-17 11:43 UTC, Shurke commented on src/homework5/task1/task1_hw_2_tasks.py
> +def count_price(price_rub, price_cop, count):
Где строки документации функций?

2021-07-17 11:43 UTC, Shurke commented on src/homework5/task1/task1_hw_4_tasks.py
> +    schoolboys_3 = [3, 'Russian', 'Italian', 'French']
Данные значения должны быть переданы в функцию, как атрибуты, а не находиться внутри.

2021-07-17 11:43 UTC, Shurke commented on src/homework5/task2.py
> +# текущий запуск программы)
Изучите пожалуйста [PEP 257](https://www.python.org/dev/peps/pep-0257/) и оформите строки документации согласно требованиям.

2021-07-17 11:43 UTC, Shurke commented on src/homework5/task4/task4_.py
> +    years_txt = open('years.txt', 'w')
Для работы с файлами стоит применять контекстные менеджеры.

2021-07-19 11:14 UTC, Jurij350 commented on src/homework5/task1/task1_hw_2_tasks.py
> +def count_price(price_rub, price_cop, count):
Добавил.

2021-07-20 06:57 UTC, Jurij350 commented on src/homework5/task4/task4_.py
> +    years_txt = open('years.txt', 'w')
Исправил через контекстный менеджер.

2021-07-20 06:59 UTC, Jurij350 commented on src/homework5/task1/task1.py
> +def runner():
Предложил другой вариант функции runner(). Теперь она одна но через ветвления выбираетсся сигнатура.

2021-07-24 10:02 UTC, Shurke reviewed
Итоговая оценка - 4.

2021-07-24 10:02 UTC, Shurke commented on src/homework5/task4/task4_.py
> +                if 28 <= i <= 278:
Что значат данные магические числа?

2021-07-24 10:02 UTC, Shurke commented on src/homework5/task4/task4_.py
> +    top_250_movies_txt.close()
Зачем, если открытие каждого файла находится в менеджере контекста?

2021-07-24 10:02 UTC, Shurke commented on src/homework5/task6.py
> +"""
Почему данная задача не оформлена как функция?

2021-07-28 05:24 UTC, closed without merging