Homework5
Shurke/it-academy-summer-2021 pull request #53
Opened 2021-07-10 12:30 UTC by DudarDN

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-07-17 11:33 UTC, Shurke requested changes

2021-07-17 11:33 UTC, Shurke commented on src/homework5/task1.py
> +    number = int(input("Введите количество товара(шт.): "))
Это обсуждалось на одной из лекций.
Функция должна получить данные значения на вход, как передаваемые атрибуты.
При написании и проектировании функций, нужно исходить из того, что функция выполняет одно действие.

2021-07-17 11:33 UTC, Shurke commented on src/homework5/task1.py
> +"""
Это должно быть оформлено в качестве строки документации для функции.

2021-07-17 11:33 UTC, Shurke commented on src/homework5/task1.py
> +
И для чего в каждом описании имеется пустая строка?

2021-07-17 11:33 UTC, Shurke commented on src/homework5/task1.py
> +            func()
Данный подход не является гибким.
Любое изменение (добавление или удаление функции) приведет к ручной работе.

2021-07-17 11:33 UTC, Shurke commented on src/homework5/task2.py
> +    results = []
После окончания выполнения данного кода и завершения работы интерпретатора, данное значение будет удалено.

2021-07-17 11:33 UTC, Shurke commented on src/homework5/task4/task4.py
> +    print("No such file")
Для чего этот код?

2021-07-19 17:45 UTC, Shurke requested changes

2021-07-19 17:45 UTC, Shurke commented on src/homework5/task1.py
> +
Ответа на свой вопрос я не получил.)

2021-07-19 17:45 UTC, Shurke commented on src/homework5/task1.py
> +        str_country_and_cities = (input("Введите сначала страну, "
Ваша программа должна получить все данные в рамках передаваемых аргументов функции.
И если в итоге запустить `runner`, то данный код корректно не отработает.

2021-07-19 17:45 UTC, Shurke commented on src/homework5/task1.py
> +        n_languages = int(input(f"Сколько языков знает школьник № {i}? "))
Смотрите предыдущее замечание.

2021-07-19 17:45 UTC, Shurke commented on src/homework5/task1.py
> +            start = globals()[func_name]
Изящно.)

2021-07-19 17:45 UTC, Shurke commented on src/homework5/task1.py
> +    if name.startswith("__") and name.endswith("__"):
В принципе, достаточно проверки начала имени.

2021-07-19 17:45 UTC, Shurke commented on src/homework5/task1.py
> +        continue
Почему для `ascii_letters` сделано исключение?

2021-07-19 17:45 UTC, Shurke commented on src/homework5/task4/task4.py
> +            is_read = True
Для чего нужна данная переменная?

2021-07-19 17:45 UTC, Shurke commented on src/homework5/task5.py
> +"""
Тогда это должно быть строкой документации функции.)

2021-07-19 17:45 UTC, Shurke commented on src/homework5/task6.py
> +"""
Смотрите комментарий выше.

2021-07-19 20:59 UTC, DudarDN commented on src/homework5/task4/task4.py
> +            is_read = True
Это флаг. Пока мы читаем построчно файл, у нас срабатывает continue до момента, когда мы доходим до строки "New  Distribution  Votes  Rank  Title\n". После этого программа меняет значение is_read на True и когда мы читаем файл дальше - continue уже не срабатывает. И мы работаем с нужными нам строками файла.

2021-07-19 21:03 UTC, DudarDN commented on src/homework5/task1.py
> +        continue
Т.к. ascii_letters - это импорт, а не функция.

2021-07-22 09:07 UTC, DudarDN commented on src/homework5/task5.py
> +"""
Исправил.

2021-07-22 09:07 UTC, DudarDN commented on src/homework5/task6.py
> +"""
Исправил. )

2021-07-24 13:43 UTC, Shurke reviewed
Итоговая оценка - 8.

2021-07-24 13:43 UTC, Shurke commented on src/homework5/task4/task4.py
> +        top_250 = top_250[1:-1]
В данном случае, индексы являются магическими числами, происхождение которых не ясно.
Любое изменение в структуре `ratings.list` потенциально ломает ваш код.
Более разумным решение было бы использовать регулярное выражение для поиска строки с нужными данными. Да, это не идеально решение, поменяли структуру файла (формат того в каком порядке записаны в строке данные) и код может перестать работать корректно. Но, все же регулярка дает большую гибкость и вариативность настройки.

2021-08-10 21:19 UTC, closed without merging