Homework5: Vitali Varabyeu
Shurke/it-academy-summer-2021 pull request #57
Opened 2021-07-13 06:21 UTC by Varabyeu

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-07-17 09:58 UTC, Shurke requested changes

2021-07-17 09:58 UTC, Shurke commented on src/task1.py
> +    s = int(input("Введите количество товаров, шт.: "))
Это обсуждалось на одной из лекций.
Функция должна получить данные значения на вход, как передаваемые атрибуты.
При написании и проектировании функций, нужно исходить из того, что функция выполняет одно действие.

2021-07-17 09:58 UTC, Shurke commented on src/task1.py
> +    # Напишите программу, которая считает общую цену.
Пожалуйста, прочтите [PEP 257](https://www.python.org/dev/peps/pep-0257/) и оформите строки документации соответствующим образом.

2021-07-17 09:58 UTC, Shurke commented on src/task1.py
> +def runner(*args):
1. Ваше решение не выполняет поставленных условием задач.
2. Само по себе решение не является гибким и при добавлении/удалении функций придется вносить изменения руками.

2021-07-17 09:58 UTC, Shurke commented on src/task2.py
> +    saved_result = []
Как только программа будет выполнена, то история будет очищена.

2021-07-17 09:58 UTC, Shurke commented on src/task4.py
> +    print("File lost")
Я этот кусок кода вижу уже в 5 решении.
Для чего оно нужно, если вы в 18 строке открываете заново данный файл?

2021-07-21 09:03 UTC, Varabyeu commented on src/task1.py
> +    s = int(input("Введите количество товаров, шт.: "))
Заменил значения на вход аргументами со значением по умолчанию

2021-07-21 09:03 UTC, Varabyeu commented on src/task1.py
> +    # Напишите программу, которая считает общую цену.
Переделал строки документации

2021-07-21 09:05 UTC, Varabyeu commented on src/task1.py
> +def runner(*args):
1. Дочитал условие задачи до конца и выполнил условие)
2. Разбил решение задачи с одного модуля на модуль с самой функцией runner и импортируемые модули по hw2-hw4

2021-07-21 09:05 UTC, Varabyeu commented on src/task2.py
> +    saved_result = []
Теперь программа записывает все значения в текстовый файл

2021-07-24 13:23 UTC, Shurke reviewed
Итоговая оценка - 7.5.

2021-07-24 13:23 UTC, Shurke commented on src/hw2_for_task1.py
> +            i += 1
Нет никакого вывода данных из программы. Т.е. по итогу, ничего для пользователя не произойдет.

2021-07-24 13:23 UTC, Shurke commented on src/task1.py
> +            call_def()
Составление одного общего списка всех функций позволит избежать дублирование кода.
В данном случае дублирование кода является неоправданным и легко устраняется.

2021-07-24 13:23 UTC, Shurke commented on src/task1.py
> +                call_def()
Здесь также возможно избежать дублирование кода.

2021-07-24 13:23 UTC, Shurke commented on src/task2.py
> +            f.write(str(result_fun) + ' ')
Мы уже изучили менеджеры контекста.

2021-08-14 12:57 UTC, closed without merging