Homework5: Sviatlana_Bernatskaya
Shurke/it-academy-summer-2021 pull request #61
Opened 2021-07-15 14:37 UTC by SvBern

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-07-17 08:13 UTC, Shurke requested changes

2021-07-17 08:13 UTC, Shurke commented on src/Homework5/Task1/Runner.py
> +        Homework2.more_long_word()
Данный подход не является гибким. Каждое изменение в одном из модулей будет приводить к ручной работе в данном файле.
Пример того, как можно автоматизировать данное действие рассматривался на лекции, когда рассматривали Примесные классы.

2021-07-17 08:13 UTC, Shurke commented on src/Homework5/Task1/Runner.py
> +import Homework4
Имена модулей следует именовать с маленькой буквы.

2021-07-17 08:13 UTC, Shurke commented on src/Homework5/Task2.py
> +    list_results = []
Как только закончится выполнение программы, данный список будет удален.
Следовательно условие задачи не выполняется.

2021-07-17 08:13 UTC, Shurke commented on src/Homework5/Task3.py
> +        print(i, end=",")
Рекомендую сделать `end=", "` и вывод более симпатичный.

2021-07-17 08:13 UTC, Shurke commented on src/Homework5/Task4/Task4.py
> +            if 28 <= num <= 277:
Что значат эти магические числа?

2021-07-17 08:13 UTC, Shurke commented on src/Homework5/Task4/Task4.py
> +    year.close()
Для чего это, если работа с данными файлами обернута в контекстные менеджеры?

2021-07-17 08:44 UTC, Shurke commented on src/Homework5/Task1/Runner.py
> +runner(func1=Homework4.check_country(), func2=Homework4.diff_num_in_one())
В условии задачи подразумевается, что имя функции будет передано как строка.
В вашем случае, вы в `runner` передается уже вызванную функцию, что не по условию задачи.

2021-07-23 17:38 UTC, SvBern commented on src/Homework5/Task4/Task4.py
> +            if 28 <= num <= 277:
С 28-й строки в файле начинается список фильмов, на 277-й заканчивается список из 250

2021-07-23 17:39 UTC, SvBern commented on src/Homework5/Task4/Task4.py
> +            if 28 <= num <= 277:
Такое решение не подходит?

2021-07-24 10:25 UTC, Shurke reviewed
Итоговая оценка - 7.5.

2021-07-24 10:25 UTC, Shurke commented on src/Homework5/Task1/Runner.py
> +list_func4 = [elem[0] for elem in getmembers(homework4) if isfunction(elem[1])]
Что мешает создать один единственный список?

2021-07-24 10:25 UTC, Shurke commented on src/Homework5/Task1/Runner.py
> +            call_def()
Переход на один список, который хранит все функции позволит избежать дублирование кода.
В данном случае, дублирование кода является неоправданным и легко избегается.

2021-07-24 10:25 UTC, Shurke commented on src/Homework5/Task1/Runner.py
> +                call_def()
Здесь также имеется место для упрощения и оптимизации кода.

2021-07-24 10:25 UTC, Shurke commented on src/Homework5/Task1/Runner.py
> +"""
Имя модуля должно начинаться с маленькой буквы.

2021-07-24 10:25 UTC, Shurke commented on src/Homework5/Task1/Runner.py
> +import homework4
Во время выполнения импорта, выполняется код в модулях, которые вы импортируете.
Следует быть острожным с применением функции `print` для вывода решения на экран.
Лучше возвращать подготовленные данные и после этого в `runner` их выводить на экран.

2021-07-24 10:25 UTC, Shurke commented on src/Homework5/Task1/homework4.py
> +        country = item.split()
Имя переменной не совсем точно передает то, что хранится в в ней.

2021-07-24 10:25 UTC, Shurke commented on src/Homework5/Task1/homework4.py
> +    name_city_list = ['Odessa', 'Moscow', 'Novgorod']
По логике, данный список должен идти сразу же за `kwargs` в 40-й строке.

2021-07-24 10:25 UTC, Shurke commented on src/Homework5/Task4/Task4.py
> +            if 28 <= num <= 277:
Как только изменится структура `ratings_list.txt`, то ваша программа перестанет корректно работать. 
Привязываться к структура файла - это не очень удачное решение. Более удачным решением было бы выделение паттернов нужной строки, обработка нужной строки и так далее.

2021-08-10 18:06 UTC, closed without merging