Homework6: Dmitry Dudar
Shurke/it-academy-summer-2021 pull request #62
Opened 2021-08-05 21:08 UTC by DudarDN

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-08-08 10:32 UTC, Shurke requested changes
Строки документации в методах и тестах не обнаружены. Исправить.

2021-08-08 10:32 UTC, Shurke commented on src/homework6/task1/BookingData.py
> +
Это принципиальная позиция не писать ни единой строки документации?

2021-08-08 10:32 UTC, Shurke commented on src/homework6/task1/Booking.py
> +class Booking:
Согласно РЕР8:
> Модули должны иметь короткие имена, состоящие из маленьких букв. Можно использовать символы подчеркивания, если это улучшает читабельность. То же самое относится и к именам пакетов, однако в именах пакетов не рекомендуется использовать символ подчёркивания.

У вас же имена модулей с большой буквы.

2021-08-08 10:32 UTC, Shurke commented on src/homework6/task1/BookingData.py
> +            if phone_number == booking.customer_id:
Более логично сделать `self.bookings` словарем, где в качестве ключа будет `phone_number`.
Это позволит убрать и цикл, и проверку условия.

2021-08-08 10:32 UTC, Shurke commented on src/homework6/task1/BookingData.py
> +                self.bookings.remove(booking)
И так же в этом методе все будет проще, если сделать `self.bookings` словарем.

2021-08-08 10:32 UTC, Shurke commented on src/homework6/task1/CarRentalService.py
> +        return cars
Будем справедливы, что искать можно и по цене, и по количеству мест, и по марке и т.д.
Стоит расширить возможный способ поиска.

2021-08-08 10:32 UTC, Shurke commented on src/homework6/task1/CarData.py
> +            if license_plate == auto.license_plate:
Точно такая же ошибка, как и выше. Номер автомобиля является уникальным значением, что позволяет однозначно идентифицировать автомобиль. Следовательно, использование номера автомобиля в качестве ключа словаря позволит вам избежать необходимости перебора всех автомобилей.

2021-08-08 10:32 UTC, Shurke commented on src/homework6/task1/main.py
> +while count < 2:
Подобного рода программы можно делать в рамках бесконечного цикла. Проверяя ввод с клавиатуры.
Допустим, задать для выхода слова "выход". 
Тогда пользователь может сколько угодно работать в вашей программе.

2021-08-08 10:32 UTC, Shurke commented on src/homework6/task3/test_hw_4_task_5.py
> +                               "German"])
В данном случае, списки с языками являются константами, т.к. повторяются в тестах. Следовательно, можно вынести на верхний уровень модуля и переиспользовать.

2021-08-08 10:32 UTC, Shurke commented on src/homework6/task3/test_hw_4_task_5.py
> +                                           student_3={"France"})
Вы в тесте осуществляется вызов функции `all_languages` с различными входными данными несколько раз. Следовательно, тест может быть преобразован и параметризован с помощью `ddt`.

2021-08-08 10:32 UTC, Shurke commented on src/homework6/task3/test_hw_4_task_5.py
> +    def test_negative(self):
Негативных сценариев может быть куда больше, чем вы проверили.

2021-08-08 10:32 UTC, Shurke commented on src/homework6/task4/task4.py
> +В качестве ответа приведите последние 9 цифр полученного числа.
А где вывод 9 цифр ответа?)

2021-08-08 10:32 UTC, Shurke commented on src/tests/hw_2/task1/test_task1.py
> +        self.assertEqual(result, "Общая цена составит 36 рублей 0 копеек.")
Тело тестов одинаковое, следовательно можно объединить в один тест, расширив `@ddt.data`.

2021-08-08 10:32 UTC, Shurke commented on src/tests/hw_2/task1/test_task1.py
> +            task1.total_price(8, 7, 7, number=5)
Точно такое же замечание.

2021-08-08 10:32 UTC, Shurke commented on src/tests/hw_2/task6/test_task6.py
> +        self.assertEqual(result, "Это палиндром!")
По факту, это все еще один тест. Стоит объединить.

2021-08-08 10:32 UTC, Shurke commented on src/tests/hw_2/task6/test_task6.py
> +            task6.palindrome(12221, 75)
Такое же замечание.

2021-08-08 10:32 UTC, Shurke commented on src/tests/hw_3/task4/test_task4.py
> +        self.assertEqual(result, "Количество пар чисел: 4")
Вас самого не смущает, что одинаковые тесты разнесены в два теста?)

2021-08-10 21:20 UTC, DudarDN commented on src/homework6/task1/BookingData.py
> +
Исправил.

2021-08-10 21:21 UTC, DudarDN commented on src/homework6/task1/Booking.py
> +class Booking:
Исправил.

2021-08-10 21:21 UTC, DudarDN commented on src/homework6/task1/BookingData.py
> +            if phone_number == booking.customer_id:
Done.

2021-08-10 21:21 UTC, DudarDN commented on src/homework6/task1/BookingData.py
> +                self.bookings.remove(booking)
Done.

2021-08-10 21:22 UTC, DudarDN commented on src/homework6/task1/CarData.py
> +            if license_plate == auto.license_plate:
Сделано.

2021-08-10 21:22 UTC, DudarDN commented on src/homework6/task1/main.py
> +while count < 2:
Done.

2021-08-10 21:28 UTC, DudarDN commented on src/homework6/task3/test_hw_4_task_5.py
> +                               "German"])
Списки языков, а также их количество отличаются в различных тестах. Также для тестирования используются различные типы данных.

2021-08-10 21:28 UTC, DudarDN commented on src/homework6/task3/test_hw_4_task_5.py
> +    def test_negative(self):
Добавил.

2021-08-11 11:21 UTC, DudarDN commented on src/homework6/task3/test_hw_4_task_5.py
> +                                           student_3={"France"})
К сожалению при помощи ddt нельзя протестировать функцию со значениями по умолчанию а также с различным количеством и типом принимаемых аргументов. Поэтому в этой задаче было принято решение не использовать ddt.

2021-08-11 11:33 UTC, DudarDN commented on src/homework6/task4/task4.py
> +В качестве ответа приведите последние 9 цифр полученного числа.
Решил поберечь Ваш компьютер и не записывать в программе вычисление числа 3^37, т.к. последствия могут быть непредсказуемые.) Мое решение работает, но, к сожалению, для чисел значительно меньше. Я нашел правильное решение в интернете, и оно находится за гранью понимания для меня. Не вижу смысла тупо копировать, не понимая логики функции. Вот ссылка, если интересно:
https://titanwolf.org/Network/Articles/Article?AID=e6733b5b-8a58-4366-b9ea-7df7b90a6659#gsc.tab=0

2021-08-11 14:35 UTC, DudarDN commented on src/tests/hw_2/task6/test_task6.py
> +        self.assertEqual(result, "Это палиндром!")
См. выше. )

2021-08-11 14:35 UTC, DudarDN commented on src/tests/hw_2/task1/test_task1.py
> +            task1.total_price(8, 7, 7, number=5)
См. выше. )

2021-08-11 14:35 UTC, DudarDN commented on src/tests/hw_3/task4/test_task4.py
> +        self.assertEqual(result, "Количество пар чисел: 4")
См. выше. )

2021-08-11 14:35 UTC, DudarDN commented on src/tests/hw_2/task1/test_task1.py
> +        self.assertEqual(result, "Общая цена составит 36 рублей 0 копеек.")
В ddt не получится смоделировать ситуацию, когда функция принимает разное количество или тип аргументов. Или не принимает их вовсе. Писал Вам по этому поводу. Строки документации разместил.

2021-08-11 17:27 UTC, DudarDN commented on src/homework6/task1/CarRentalService.py
> +        return cars
Добавил возможность поиска автомобиля по марке. Так же, теперь, если в списке нет машин соответствующих запросу пользователя, программа будет автоматически завершаться.

2021-08-14 12:56 UTC, Shurke requested changes
В части тестах наблюдается явление, когда вы вызываете несколько раз тестируемую функцию с различными входными данными и осуществляется различные проверки.
В ряде случае, справедливо отметить, что тест не может быть сведен к какому-то общему случаю и параметризации. В таком случае, каждый тестовый кейс (вызов тестируемой функции и проверка) должны быть разнесены в различные тесты.
Но, остается еще достаточно тестов, которые можно все таки параметризовать.

2021-08-14 12:56 UTC, Shurke commented on src/homework6/task1/booking.py
> +    (уникальные параметры клиента и авто).
Вот это и должно быть описано именно в конструкторе.

2021-08-14 12:56 UTC, Shurke commented on src/homework6/task1/booking_data.py
> +    def get_bookings(self, phone_number):
Имя метода подразумевает возвращение нескольких броней, а не одной. Исходя из строки документации метода, то возвращается одна бронь.

2021-08-14 12:56 UTC, Shurke commented on src/homework6/task1/car.py
> +    автомобиля, а также стоимость аренды в сутки.
Это строка документации конструктора, а не часть строки документации класса.

2021-08-14 12:56 UTC, Shurke commented on src/homework6/task1/car_data.py
> +    def find_by_seats_price_model(self, seats, price, model):
А что если клиент что-то не ввел?

2021-08-14 12:56 UTC, Shurke commented on src/homework6/task1/main.py
> +        model = UserInterface.ask_for_model()
К комментарию выше о том, что клиент что-то не ввел.
Не увидел обработки пустой строки, которая тут может быть передана в программу.

2021-08-14 12:56 UTC, Shurke commented on src/homework6/task1/main.py
> +        result_cars = car_service.search(seats, budget, model)
Исходя из логики, то данный метод по поиску автомобиля должен вызываться внутри метода `let_user_chose_car`.

2021-08-14 12:56 UTC, Shurke commented on src/homework6/task3/test_hw_4_task_5.py
> +    def test_negative(self):
И по итогу тесте получилось две различные проверки.
Чего быть не должно.
Стоит вынести в отдельный тест проверку `assertRaises` и параметризовать его.

2021-08-14 12:56 UTC, Shurke commented on src/homework6/task3/test_hw_4_task_5.py
> +                                           student_3={"France"})
У вас в рамках одного теста несколько различных вызовов тестируемой функции и проверок.
Если тест нельзя параметризировать, то стоит разделить тестовые случаи и оформить отдельными тестами.

2021-08-15 22:43 UTC, DudarDN commented on src/homework6/task1/booking.py
> +    (уникальные параметры клиента и авто).
Исправил.

2021-08-15 22:44 UTC, DudarDN commented on src/homework6/task1/booking_data.py
> +    def get_bookings(self, phone_number):
Исправил название метода.

2021-08-15 22:44 UTC, DudarDN commented on src/homework6/task1/car.py
> +    автомобиля, а также стоимость аренды в сутки.
Исправил.

2021-08-15 22:52 UTC, DudarDN commented on src/homework6/task1/main.py
> +        model = UserInterface.ask_for_model()
Добавил значения по умолчанию в случае ввода некорректных параметров. Также обработал случай, если клиент вводит некорректный номер телефона при возврате авто.

2021-08-15 22:52 UTC, DudarDN commented on src/homework6/task1/car_data.py
> +    def find_by_seats_price_model(self, seats, price, model):
Теперь если клиент ничего не ввел, либо его ввод является некорректным, сработают значения по умолчанию.

2021-08-22 13:09 UTC, Shurke reviewed
Итоговая оценка - 7.5.

2021-08-22 13:09 UTC, Shurke commented on src/homework6/task1/booking.py
> +        Принимает номер телефона клиента и государственный номер
`customer_id` - это номер телефона клиента?

2021-08-22 13:09 UTC, Shurke commented on src/homework6/task1/car_data.py
> +    def find_by_seats_price_model(self, seats, price, model):
Преемлимо.)

2021-08-22 13:09 UTC, Shurke commented on src/homework6/task1/car_rental_service.py
> +        Принимает экземпляры классов,
Класс ничего не принимает.

2021-08-22 13:09 UTC, Shurke commented on src/homework6/task1/car_rental_service.py
> +        """Возвращает список авто по введенным клиентом параметрам"""
Нет описания принимаемых параметров.

2021-08-22 13:09 UTC, Shurke commented on src/homework6/task1/customer.py
> +        self.phone = phone
В классах выше фигурирует `customer_id`, который в классе `Customer` отсутсвует в явном виде.

2021-08-22 13:09 UTC, Shurke commented on src/homework6/task1/main.py
> +        model = UserInterface.ask_for_model()
Преемлимо.

2021-08-22 13:09 UTC, Shurke commented on src/homework6/task3/test_hw_4_task_5.py
> +import hw_4_task_5
Нет докстринги тестового модуля.

2021-08-22 13:09 UTC, Shurke commented on src/homework6/task3/test_hw_4_task_5.py
> +class Test(unittest.TestCase):
1. Нет докстринги тестового класса.
2. Имя тестового класса слишком общее.

2021-08-23 11:01 UTC, DudarDN commented on src/tests/hw_2/task6/test_task6.py
> +        self.assertEqual(result, "Это палиндром!")
def test_positive_2(self):
        result = task6.palindrome()
        self.assertEqual(result, "Это палиндром!")

2021-08-28 08:37 UTC, closed without merging