Homework6: Anton Doroshenko
Shurke/it-academy-summer-2021 pull request #63
Opened 2021-08-07 15:12 UTC by AntonDoroshenko

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-08-08 11:44 UTC, Shurke requested changes
Пересмотреть тесты.
Многие тесты написаны ради того, чтобы быть. Смысла в их наличии нет, т.к. ничего конкретного они не тестируют.

2021-08-08 11:44 UTC, Shurke commented on src/homework6/task1.py
> +class Power_of_friendship(Good_character):
Не совсем понимаю, как сила дружбы соотносится с классом игрового персонажа.

2021-08-08 11:44 UTC, Shurke commented on src/homework6/task1.py
> +main_person_1.introduce_game_persons()
Более логичным сделать метод `introduce_game_persons` отдельной функцией. В которой определить несколько шаблонов приветствия и организовать рандомный выбор шаблона. В саму функцию передать имя персонажа, которого необходимо приветствовать.

2021-08-08 11:44 UTC, Shurke commented on src/homework6/task1.py
> +                            'валерийская сталь')
На мой взгляд, стоило предусмотреть у игрового персонажа атрибут экземпляра, который будет принимать в себя экземпляр оружия, к примеру `self.weapon = Weapon(...)`. И сам класс оружия будет логичнее сделать более общим, чтобы не только `Good_character` мог бы быть им экипирован.

2021-08-08 11:44 UTC, Shurke commented on src/homework6/task2.py
> +    """
Опять же, условие должно быть строкой документации модуля.

2021-08-08 11:44 UTC, Shurke commented on src/homework6/task2.py
> +                    raise TooManyErrors('TooManyErrors')
Исключение возбуждается по превышению количества попыток вызова без исключений. Следовательно, текст исключения должен об этом сообщать. `TooManyErrors` не несет явной информации о том, что произошло.

2021-08-08 11:44 UTC, Shurke commented on src/unittests/tests_HW2/test.task_5_fibonachi.py
> +import ddt
Почему вы принципиально игнорируете PEP8?

> Модули должны иметь короткие имена, состоящие из маленьких букв. Можно использовать символы подчеркивания, если это улучшает читабельность. То же самое относится и к именам пакетов, однако в именах пакетов не рекомендуется использовать символ подчёркивания.

2021-08-08 11:44 UTC, Shurke commented on src/unittests/tests_HW2/test.task_5_fibonachi.py
> +        (100, 218922995834555169026),
Принимая во внимание, что в вашем варианте вычисления числа Фибоначи нет кеширования, то данное значение будет не так уж и быстро считаться. Да и смысла в таком огромном числе для проверки нет.

2021-08-08 11:44 UTC, Shurke commented on src/unittests/tests_HW2/test.task_5_fibonachi.py
> +        """проверка на отрицательный результат выполнения программы"""
Если рассматривать вашу функцию, то возможно на самом деле два варианта развития события:
1. функция отработала и посчитала верно (позитивный сценарий). Он уже реализован и позволит контролировать правильность работы.
2. Функция упадет с ошибкой, т.к. на вход передан не верный формат данных или в принципе входных данных не было.

Следовательно, остальные тесты будут излишними в данном случае.

2021-08-08 11:44 UTC, Shurke commented on src/unittests/tests_HW2/task_6_polindrom.py
> +    return n2
Исходя из условия, функция должна давать ответ на вопрос "является ли число палиндромом", т.е. возвращать `True` или `False`, `Палиндром` или `Не палиндром`, а не какое-то число.
И на основании этого уже строить тестирование.

2021-08-08 11:44 UTC, Shurke commented on src/unittests/tests_HW2/test.task_6_polindrom.py
> +        self.assertEqual(res, expect_num)
Смотрите замечание в модуле с функцией.

2021-08-08 11:44 UTC, Shurke commented on src/unittests/tests_HW3/test.task_2_list_pract.py
> +        self.list_pr = My_Func_3_2()
Вот только вы создали экземпляр класса, а не вызвали функцию.

2021-08-08 11:44 UTC, Shurke commented on src/unittests/tests_HW3/test.task_2_list_pract.py
> +        res = self.list_pr.second_lst(l_1)
В вашем случае, метод `second_lst` зависит от результата работы `first_lst`. Т.е. присутствует зависимость. И для более правильного тестирования, вам стоило замокать `first_lst`, чтобы изолированно протестировать `second_lst`.
Данное замечание также справедливо и для тестирования `final_lst`.

2021-08-08 11:44 UTC, Shurke commented on src/unittests/tests_HW3/task_2_list_pract.py
> +        return final_lst
Все методы должны быть помечены как `@staticmethod`, т.к. ни в одном из них нет вызова `self`.

2021-08-08 11:44 UTC, Shurke commented on src/unittests/tests_HW3/test.task_6_list.py
> +        self.assertCountEqual(res, compare_list)
В чем смысл данного теста относительно того, что выполняет функция?

2021-08-08 11:44 UTC, Shurke commented on src/unittests/tests_HW3/test.task_6_list.py
> +        self.assertIn(4, res)
Для чего данный тест нужен, если результат правильной работы тестируется выше?

2021-08-08 11:44 UTC, Shurke commented on src/unittests/tests_HW4/test.task_2_cities_and_country.py
> +# Согласно условию задачи, все города и страны уже заложенны в программу
Это согласно вашей реализации для прошлой домашней задачи, а не условию задачи.
В данном случае более верно было бы реализовать передачу всех входных значений для функции в качестве ее аргументов.

2021-08-08 11:44 UTC, Shurke commented on src/unittests/tests_HW4/test.task_3_different_number.py
> +        """Положительный результат выполнения программы"""
Строки документации в таком стиле не несут никакого смысла о том, что и как тестируется.

2021-08-08 11:44 UTC, Shurke commented on src/unittests/tests_HW5/test.task_5_nearst_degree.py
> +        self.assertEqual(res, expected)
Помимо возвращаемого значения, ваша программа еще и печатает текст на экран.
Следовательно, печать текста на экран следует тестировать.

2021-08-08 11:44 UTC, Shurke commented on src/unittests/tests_HW5/test.task_5_nearst_degree.py
> +        self.assertLess(res, expected)
В чем смысл данного теста?
Как его наличие влияет на что-то?

2021-08-18 14:55 UTC, AntonDoroshenko commented on src/homework6/task1.py
> +     """
Исправил

2021-08-18 14:56 UTC, AntonDoroshenko commented on src/homework6/task1.py
> +class Game_person:
Исправил

2021-08-18 15:18 UTC, AntonDoroshenko commented on src/homework6/task1.py
> +        print(f'Против нашего героя будет биться {self.person_name}!!!')
Выглядит может оно и так, оданко я передаю параметры для класса Master, который в свою очередь наследуется от класса GamePerson  где формируется мой персонаж.  А так называемый герой формируется уже когда я передаю параметры для класса GoodCharacter, который так же наследуется от родительского GamePerson. Используя одинаковые названия def introduce_game_persons(self)  я хотел показать наличия полиморфизма в своей модели.

2021-08-18 15:24 UTC, AntonDoroshenko commented on src/homework6/task1.py
> +class Power_of_friendship(Good_character):
Я этому классу заново передавал информацию о герое, а от класса хороший персонаж хотел наследовать его конструкцию.

2021-08-18 15:28 UTC, AntonDoroshenko commented on src/homework6/task2.py
> +    """
Исправил

2021-08-18 15:28 UTC, AntonDoroshenko commented on src/homework6/task2.py
> +                    raise TooManyErrors('TooManyErrors')
Исправил

2021-08-18 15:49 UTC, AntonDoroshenko commented on src/unittests/tests_HW2/test.task_5_fibonachi.py
> +import ddt
Просто я давненько не пересматривал PEP8.
Исправил.
И хочу ответить про замечание об наличии ненужных тестов. Я подумал что необходимо было сделать все возможные тесты для программы.  Просто открыв список ассертов подбирал подходящие и формировал тесты не изменяя саму программу.

2021-08-18 15:54 UTC, AntonDoroshenko commented on src/unittests/tests_HW2/test.task_5_fibonachi.py
> +        (100, 218922995834555169026),
Исправил

2021-08-18 16:02 UTC, AntonDoroshenko commented on src/unittests/tests_HW2/test.task_5_fibonachi.py
> +        """проверка на отрицательный результат выполнения программы"""
Понял.
Добавил проверку отсутствия входных данных.

2021-08-18 16:14 UTC, AntonDoroshenko commented on src/unittests/tests_HW2/task_6_polindrom.py
> +    return n2
Исправил

2021-08-18 16:14 UTC, AntonDoroshenko commented on src/unittests/tests_HW2/test.task_6_polindrom.py
> +        self.assertEqual(res, expect_num)
+

2021-08-18 16:17 UTC, AntonDoroshenko commented on src/unittests/tests_HW3/test.task_2_list_pract.py
> +        self.list_pr = My_Func_3_2()
self. - экземпляр.
Я знаю, просто думал об одном, печатал другое)

2021-08-18 16:22 UTC, AntonDoroshenko commented on src/unittests/tests_HW3/task_2_list_pract.py
> +        return final_lst
Исправил

2021-08-18 16:55 UTC, AntonDoroshenko commented on src/unittests/tests_HW3/test.task_6_list.py
> +        self.assertCountEqual(res, compare_list)
Как я описал ранее:  изучая разные ассерты пытался применить их к тестированию модуля в рамках дозволенного.
В данном случае, применил ассерт который проверяет наличие одинаковых элементов независимо от их расположения в списке.

2021-08-18 16:57 UTC, AntonDoroshenko commented on src/unittests/tests_HW3/test.task_6_list.py
> +        self.assertIn(4, res)
Подумал что данный ассерт можно так же применить к тестированию модуля. Пытался реализовать все возможные ассерты.

2021-08-18 16:58 UTC, AntonDoroshenko commented on src/unittests/tests_HW4/test.task_3_different_number.py
> +        """Положительный результат выполнения программы"""
Убрал

2021-08-18 17:01 UTC, AntonDoroshenko commented on src/unittests/tests_HW5/test.task_5_nearst_degree.py
> +        self.assertLess(res, expected)
Пробовал реализовать как можно больше ассертов. Убрал данный тест.

2021-08-22 13:19 UTC, Shurke reviewed
Итоговая оценка - 7.

2021-08-22 13:19 UTC, Shurke commented on src/homework6/task1.py
> +import random
В рамках первой задачи, строки документации классов и методов отсутствуют как таковые.

2021-08-22 13:19 UTC, Shurke commented on src/homework6/task1.py
> +pof.mystery_of_the_battle()
Было бы более интересно, если все же реализовали простую боевку.
Но это скорее придирка.

2021-08-22 13:19 UTC, Shurke commented on src/unittests/tests_HW2/task_5.py
> +    return fib_1
По-хорошему счету, то `print` здесь уже не нужен.

2021-08-22 13:19 UTC, Shurke commented on src/unittests/tests_HW2/task_6.py
> +        return False
Можно компактнее написать.
```python
return b == n2
```

2021-08-28 08:37 UTC, closed without merging