homework6: Jurij Stankiewich
Shurke/it-academy-summer-2021 pull request #65
Opened 2021-08-10 06:26 UTC by Jurij350

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-08-14 12:43 UTC, Shurke requested changes
Обращаю внимание на строки документации.
Во многих функциях они оформлены как простой однострочный комментарий. В большинстве тестов их нет для тестовых классов и тестовых функций.

2021-08-14 12:43 UTC, Shurke commented on src/homework6/task1.py
> +        return answer
Данный метод никак не относится к билету.

2021-08-14 12:43 UTC, Shurke commented on src/homework6/task1.py
> +            return 'Please come in! '
Этот метод не относится к билету.

2021-08-14 12:43 UTC, Shurke commented on src/homework6/task2.py
> +            if number < cnt.counter:
Сначала стоит проверить, а потом увеличить.
И момент инкрементирования стоит добавить после вызова декорируемой функции, а не до.

2021-08-14 12:43 UTC, Shurke commented on src/homework6/task2_second_version.py
> +            cursor.execute("INSERT INTO COUNTER (id) VALUES (1)")
Опять же, увеличение счетчика должно быть осуществлено после вызова функции, а не до.

2021-08-14 12:43 UTC, Shurke commented on src/homework6/task3/test_cat_dog_years.py
> +        pass
Если ничего не определяется в данных функциях, то их можно опустить.

2021-08-14 12:43 UTC, Shurke commented on src/homework6/task4/task4_eiler.py
> +    # дроби из двух чисел
Еще раз обратитесь к РЕР8 и обратите внимание на оформление строк документации.

2021-08-14 12:43 UTC, Shurke commented on src/homework6/task4/task4_eiler.py
> +    return False
Можно ужать до
```python
return n < d and smallest_number(n, d) == 1
```

2021-08-14 12:43 UTC, Shurke commented on src/homework6/task4/task4_eiler.py
> +      " расположена непосредственно слева от 3/7."
В задаче просят назвать числительно дроби, а не всю дробь.

2021-08-14 12:43 UTC, Shurke commented on src/homework6/task4/task4_eiler.py
> +      .format(maximum_del, int(fraction[0]), fraction[1]))
Я бы рекомендовал собрать все решение в одну функцию.
Т.е. чтобы по вызову всего одной функции получать ответ.
Тогда тестирование будет более завершенным. Передали на вход значение, получили ответ.
Сейчас у вас только отдельные части решения протестированы.

2021-08-17 09:41 UTC, Jurij350 commented on src/homework6/task2.py
> +            if number < cnt.counter:
Устранил

2021-08-17 09:59 UTC, Jurij350 commented on src/homework6/task2_second_version.py
> +            cursor.execute("INSERT INTO COUNTER (id) VALUES (1)")
Устранил. Пришлось создать дополнительный класс.

2021-08-17 10:03 UTC, Jurij350 commented on src/homework6/task4/task4_eiler.py
> +      " расположена непосредственно слева от 3/7."
Устранил вывод результата

2021-08-17 10:04 UTC, Jurij350 commented on src/homework6/task4/task4_eiler.py
> +    return False
Переписал функцию

2021-08-17 10:25 UTC, Jurij350 commented on src/homework6/task1.py
> +        return answer
Устранил

2021-08-17 10:25 UTC, Jurij350 commented on src/homework6/task1.py
> +            return 'Please come in! '
странил

2021-08-17 10:36 UTC, Jurij350 commented on src/homework6/task3/test_cat_dog_years.py
> +        pass
Удалил функции в которых не было определения.

2021-08-17 11:06 UTC, Jurij350 commented on src/homework6/task4/task4_eiler.py
> +      .format(maximum_del, int(fraction[0]), fraction[1]))
Оформил в виде функции а затем протестировал все результаты на конечной функции.

2021-08-17 11:07 UTC, Jurij350 commented on src/homework6/task4/task4_eiler.py
> +    # дроби из двух чисел
Устранил

2021-08-22 13:25 UTC, Shurke reviewed
Итоговая оценка - 8.5.

2021-08-22 13:25 UTC, Shurke commented on src/homework6/task1.py
> +    def __init__(self, where_from, to, comfort_level, day):
Конструктор также должен иметь строку документации с пояснениями, какие атрибуты приходят на вход.

2021-08-22 13:25 UTC, Shurke commented on src/homework6/task2.py
> +cnt = CounterDecRun()
Инициализацию счетчика стоит делать внутри `dec_counter`, чтобы данный декоратор был независимым.

2021-08-22 13:25 UTC, Shurke commented on src/homework6/task2.py
> +            return result
Сначала стоит выполнить функцию, а потом увеличить счетчик, если функция была выполнена без исключений. В вашем случае, в 47 строке произойдет исключение, а счетчик правильных выполнений уже увеличен.

2021-08-22 13:25 UTC, Shurke commented on src/homework6/task2_second_version.py
> +cnt_second = SqliteCoutner()
См. аналогичное замечание выше.

2021-08-22 13:25 UTC, Shurke commented on src/homework6/task3/test_cat_dog_years.py
> +class TestCatDogYearsTestCase(unittest.TestCase):
Тестовый класс и тестовые случаи должны иметь строку документации.

2021-08-22 13:25 UTC, Shurke commented on src/homework6/task3/test_square_digits.py
> +class SquareDigitsTestCase(unittest.TestCase):
`TestSquareDigitsCase`

2021-08-23 08:02 UTC, closed without merging