Homework6: Sviatlana Bernatskaya
Shurke/it-academy-summer-2021 pull request #71
Opened 2021-08-10 16:38 UTC by SvBern

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-08-14 11:57 UTC, Shurke requested changes

2021-08-14 11:57 UTC, Shurke commented on src/home6/task1.py
> +    def __init__(self, name, account_num):
Стоило бы добавить строку документации и описание того, что за атрибуты будут у экземпляра.

2021-08-14 11:57 UTC, Shurke commented on src/home6/task1.py
> +    """Общий класс для банковского счета"""
Судя по названию класса, то речь идет о владельце счета, а не об описании банковского счета.

2021-08-14 11:57 UTC, Shurke commented on src/home6/task1.py
> +        return 150
Может стоило через атрибут экземпляра\класса сделать?

2021-08-14 11:57 UTC, Shurke commented on src/home6/task1.py
> +        SMSMixin.send_sms()
Исходя их того, что я вижу, то следовало бы в методе `send_sms()` предусмотреть возможность получения входных данных и формирования сообщения. Либо просто принимать уже готовое сообщение и печатать его, как уведомление для клиента по СМС.
А так, то у вас сообщение для клиента печатается вне этого метода.

2021-08-14 11:57 UTC, Shurke commented on src/home6/task1.py
> +    """Функция формирует список клиетов с номерами счетов,
Функция выводит на экран инфорацию о владельцах счетов, а не формирует список клиентов.

2021-08-14 11:57 UTC, Shurke commented on src/home6/task1.py
> +calculation_fees([
Можно было сюда еще добавить функцию, которая бы принимала ввод с клавиатуры и позволяла самому создавать себе карту, выбирая из вариантов, выпускать карты, узнавать сколько денег на счету и т.д.

2021-08-14 11:57 UTC, Shurke commented on src/home6/task2.py
> +                    n -= 1
Данный тип исключения относится к функции, для которой применен декоратор.
Задекорировав другую функцию и декоратор уже не работает корректно.

2021-08-14 11:57 UTC, Shurke commented on src/home6/task2.py
> +                                    ' неправильных попыток достигнуто!')
Как раз таки задается количество правильных попыток.

2021-08-14 11:57 UTC, Shurke commented on src/home6/task3/h2_task12/test_h2_task12.py
> +import ddt
Нет строки документации модуля

2021-08-14 11:57 UTC, Shurke commented on src/home6/task3/h2_task12/test_h2_task12.py
> +class Test(unittest.TestCase):
1. Имя тестового класса должно нести информацию о том, что тестируется.
2. Нет строки документации класса.

2021-08-14 11:57 UTC, Shurke commented on src/home6/task3/h2_task12/test_h2_task12.py
> +    def test_1(self, input_data, expected):
Имя теста также должно позволить понять, а что тестируется.

2021-08-14 11:57 UTC, Shurke commented on src/home6/task3/h2_task12/test_h2_task12.py
> +    @ddt.unpack
Луше оформлять следующим образом.
```python
@ddt.data(
    (123, TypeError),
    ([1, 2, 2, 3], AttributeError),
    ('1231123', IndexError),
)
@ddt.unpack
```

2021-08-14 11:57 UTC, Shurke commented on src/home6/task3/h3_task5/test_h3_task5.py
> +    """
Это скорее документация модуля, а не класса.

2021-08-14 11:57 UTC, Shurke commented on src/home6/task3/h3_task6/h3_task6.py
> +    pass
А с какой целью добавлено кастомное исключение?

2021-08-14 11:57 UTC, Shurke commented on src/home6/task4/euler452.py
> +    f(1, 2)
Почему функция вызывается именно с такими аргументами?

2021-08-14 11:57 UTC, Shurke commented on src/home6/task4/euler452.py
> +    def f(prod, p):
Имя функции ничего не говорит о том, что на делает.
Нет строки документации.

2021-08-21 15:30 UTC, SvBern commented on src/home6/task1.py
> +        return 150
Оставила так, чтобы было проще использовать в функции, рассчитывающей общую сумму вознаграждения банка

2021-08-21 15:31 UTC, SvBern commented on src/home6/task1.py
> +    def __init__(self, name, account_num):
Добавила

2021-08-21 15:31 UTC, SvBern commented on src/home6/task1.py
> +    """Общий класс для банковского счета"""
Да, исправила

2021-08-21 15:34 UTC, SvBern commented on src/home6/task1.py
> +        SMSMixin.send_sms()
Это была скорее фиксация банком факта отправки уведомления клиенту. Переделала, теперь фиксируется вместе с текстом сообщения для клиента. Сообщение для клиента получает входные данные.

2021-08-21 15:34 UTC, SvBern commented on src/home6/task1.py
> +    """Функция формирует список клиетов с номерами счетов,
Исправила

2021-08-21 15:37 UTC, SvBern commented on src/home6/task1.py
> +calculation_fees([
Добавила возможность выбора клиентом решения о выпуске карты и о типе выпускаемой карты. Ввод производится с клавиатуры.

2021-08-21 15:37 UTC, SvBern commented on src/home6/task2.py
> +                    n -= 1
Исправила

2021-08-21 15:37 UTC, SvBern commented on src/home6/task2.py
> +                                    ' неправильных попыток достигнуто!')
Исправила

2021-08-21 16:12 UTC, SvBern commented on src/home6/task3/h2_task12/test_h2_task12.py
> +import ddt
Добавила

2021-08-21 17:22 UTC, SvBern commented on src/home6/task3/h2_task12/test_h2_task12.py
> +class Test(unittest.TestCase):
Исправила

2021-08-21 17:23 UTC, SvBern commented on src/home6/task3/h2_task12/test_h2_task12.py
> +    def test_1(self, input_data, expected):
Исправила

2021-08-21 17:24 UTC, SvBern commented on src/home6/task3/h2_task12/test_h2_task12.py
> +    @ddt.unpack
Исправила

2021-08-21 17:29 UTC, SvBern commented on src/home6/task3/h3_task5/test_h3_task5.py
> +    """
Перенесла

2021-08-21 17:47 UTC, SvBern commented on src/home6/task3/h3_task6/h3_task6.py
> +    pass
По условию задачи список должен состоять из целых чисел. Однако, если протестировать программу без этого исключения, то она выполнится и со списком, содержащим дробное число. Поэтому пришлось немного подправить задачу

2021-08-21 21:34 UTC, SvBern commented on src/home6/task4/euler452.py
> +    f(1, 2)
Я точно не знаю, только догадываюсь. Это решение я взяла с форума по проблеме 452 сайта projecteuler.net, чтобы хоть как-то получить требуемый ответ. Вот объяснение автора: "Если извлечь числа больше 1 из допустимых кортежей и расположить их в неубывающем порядке (таким образом, цепочки [2,3,3,5,5,5] и [4,8,8,9,9,9] имеют профиль (1, 2,3)) я нашел всего 22670 уникальных профилей. Так что эта проблема не жаждет памяти". Добавляю файлы со своим решением, но с ним можно получить результат только с маленькими входными данными (до 5-6).

2021-08-21 21:36 UTC, SvBern commented on src/home6/task4/euler452.py
> +    def f(prod, p):
Я точно не знаю, что она делает. Знаю только, что в целом программа работает правильно и получает нужный результат за пару минут. Добавляю свое решение, которое работает только на маленьких числах.

2021-08-22 11:51 UTC, Shurke reviewed
Итоговая оценка - 7.

2021-08-22 11:51 UTC, Shurke commented on src/home6/task1.py
> +    def __init__(self, name, account_num):
Да, вы то добавили, но только не в конструктор.  А нужно было именно в конструктор.

2021-08-22 11:51 UTC, Shurke commented on src/home6/task1.py
> +        b = (a * self.interest_rate) / 365
А если год високосный?

2021-08-22 11:51 UTC, Shurke commented on src/home6/task1.py
> +            print('Карта к счету не выпускалась')
А чем отличается данный класс от этого же метода в `IndividualWithCard`?
На мой взгляд, отличий нет. Следовательно на лицо дублирование кода там, где его не должно быть.
Следовательно, данный метод должен находиться в общем родительском классе для `IndividualWithCard` и `LegalEntityWithCard` классов.

2021-08-22 11:51 UTC, Shurke commented on src/home6/task1.py
> +calculation_fees([
В вашем случае, логика добавлена в классы, которые реализую логику хранения данных и т.д.
Следовало бы реализовать конструкцию вида 
```python
def main():
    ...


if __name__ == '__main__':
    main()
```
И именно в функции `main()` уже осуществлять прием вводимых данных с клавиатуры и реализацию логики ответа на введенные данные. Тем самым, была бы четкая структура.

2021-08-22 11:51 UTC, Shurke commented on src/home6/task3/h3_task6/h3_task6.py
> +    pass
Из условия

> Оформите указанную задачу из прошлых домашних в виде функции и покройте тестами. Учтите, что в функцию могут быть переданы некорректные значения, здесь может пригодится ‘assertRaises’. **Не нужно переделывать функцию для того чтобы она ловила все возможные ситуации сама.**

2021-08-28 08:37 UTC, closed without merging